insert ignore into banners (banner_name, banner_price, banner_text) values ('first banner', 1 << 2, 'first banner adv text');
insert ignore into banners (banner_name, banner_price, banner_text) values ('second banner', 1 << 3, 'seconds banner adv text');
insert ignore into banners (banner_name, banner_price, banner_text) values ('third banner', 1 << 4, 'third banner adv text');
insert ignore into categories (name, request_id) values ('first category', 'request1Id');
insert ignore into categories (name, request_id) values ('second category', 'request2Id');
insert ignore into categories (name, request_id) values ('third category', 'request3Id');
insert ignore into categories (name, request_id) values ('fourth category', 'request4Id');
insert ignore into banners_categories (banner_id, category_id) VALUES (1,1);
insert ignore into banners_categories (banner_id, category_id) VALUES (1,2);
insert ignore into banners_categories (banner_id, category_id) VALUES (1,2);
insert ignore into banners_categories (banner_id, category_id) VALUES (2,1);
insert ignore into banners_categories (banner_id, category_id) VALUES (2,2);
insert ignore into banners_categories (banner_id, category_id) VALUES (2,3);
insert ignore into banners_categories (banner_id, category_id) VALUES (3,4);